@startuml component

    package "System" {
        [REST-WebInterface] as rest
        [User] as user
        [Shop] as shop
        [Duty] as duty
        [DB Connector] as db


        rest --> user
        rest --> shop
        rest --> duty 

        db --> user
        db --> shop
        db --> duty 
        rest - http

    }

    database Database
    package Frontend 

    Frontend --> http
    Database <-- db
@enduml